version: '3.5'

services:
  app:   # Change 'app' to 'frontend' for clarity
   build: 
     context: .
     dockerfile: Dockerfile
   container_name: nextjsapp
   ports:
     - "3000:3000"
   volumes:
     - .:/app
     - /app/node_modules
